name: CI
on:
  push:
    branches: main
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'

  pull_request:
  workflow_dispatch:

jobs:
  ci-test:
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/OnePlusOSS/android_kernel_5.10_oneplus_mt6983
          kernel-dir: kernel
          kernel-branch: oneplus/mt6983_v_15.0.0_ace_2v
          depth: 1
          vendor: true
          vendor-url: https://github.com/OnePlusOSS/android_kernel_modules_oneplus_mt6983
          vendor-dir: vendor
          vendor-branch: oneplus/mt6983_v_15.0.0_ace_2v
          config: k6893v1_64_k510_defconfig
          arch: arm64
          aosp-clang: true
          aosp-gcc: true
          ksu: true
          ksu-other: true
          ksu-version: susfs-stable
          ksu-url: https://github.com/ShirkNeko/SukiSU-Ultra/
          android-version: main
          lxc: true
          lxc-patch: true
          nethunter: true
          nethunter-patch: true
          ccache: true
          aosp-clang-version: r530567
          disable-lto: true
          anykernel3: true
